#!/bin/sh

bin/spark-submit \
  --deploy-mode cluster \
  --master k8s://https://spark.eastus2.cloudapp.azure.com \
  --kubernetes-namespace default \
  --conf spark.app.name=heatmap \
  --conf spark.kubernetes.driver.docker.image=timfpark/heatmap-driver:v5 \
  --conf spark.kubernetes.executor.docker.image=kubespark/spark-executor:v2.2.0-kubernetes-0.5.0 \
  --conf spark.dynamicAllocation.enabled=true \
  --conf spark.shuffle.service.enabled=true \
  --conf spark.kubernetes.shuffle.namespace=default \
  --conf spark.kubernetes.shuffle.labels="app=spark-shuffle-service,spark-version=2.2.0" \
  --conf spark.local.dir="/mnt/spark" \
  --jars local:///opt/spark/code/spark-cassandra-connector-2.0.5-s_2.11.jar \
  --py-files local:///opt/spark/code/tile.py \
  local:///opt/spark/code/heatmap.py
